import {Component} from 'react';
import {Navigate,Route,Routes} from 'react-router-dom';
import {useSelector} from 'react-redux';
import Auth from './pages/Auth.jsx';import Workspace from './pages/Workspace.jsx';import RoleDashboard from './pages/RoleDashboard.jsx';import CustomerChat from './pages/CustomerChat.jsx';
const agentPages=['waiting','active','resolved'],adminPages=['agents','settings'];
function Guard({roles,children}){const user=useSelector(s=>s.auth.user);if(!user)return <Navigate to="/login" replace/>;return roles.includes(user.role)?children:<Navigate to={user.role==='customer'?'/customer/dashboard':user.role==='agent'?'/agent/dashboard':'/admin/dashboard'} replace/>}
const customerPage=page=><Guard roles={['customer']}><RoleDashboard page={page}/></Guard>;
export default function App(){return <PageErrorBoundary><Routes><Route path="/login" element={<Auth/>}/><Route path="/register" element={<Auth/>}/><Route path="/chat" element={<Guard roles={['customer','agent']}><Workspace/></Guard>}/><Route path="/chat/:conversationId" element={<Guard roles={['customer','agent']}><Workspace/></Guard>}/><Route path="/customer/dashboard" element={customerPage('dashboard')}/><Route path="/customer/new-chat" element={customerPage('new-chat')}/><Route path="/customer/conversations" element={customerPage('conversations')}/><Route path="/customer/history" element={<Navigate to="/customer/conversations" replace/>}/><Route path="/customer/notifications" element={customerPage('notifications')}/><Route path="/customer/profile" element={customerPage('profile')}/><Route path="/customer/profile/edit" element={customerPage('edit-profile')}/><Route path="/customer/settings" element={customerPage('settings')}/><Route path="/customer/chat/:conversationId" element={<Guard roles={['customer']}><CustomerChat/></Guard>}/><Route path="/agent/dashboard" element={<Guard roles={['agent']}><Workspace/></Guard>}/><Route path="/agent/waiting" element={<Guard roles={['agent']}><Workspace/></Guard>}/><Route path="/agent/active" element={<Guard roles={['agent']}><Workspace/></Guard>}/><Route path="/agent/resolved" element={<Guard roles={['agent']}><Workspace/></Guard>}/><Route path="/agent/profile" element={<Guard roles={['agent']}><RoleDashboard page="profile"/></Guard>}/><Route path="/agent/profile/edit" element={<Guard roles={['agent']}><RoleDashboard page="edit-profile"/></Guard>}/><Route path="/agent/settings" element={<Guard roles={['agent']}><RoleDashboard page="settings"/></Guard>}/><Route path="/agent/notifications" element={<Guard roles={['agent']}><RoleDashboard page="notifications"/></Guard>}/><Route path="/admin/dashboard" element={<Guard roles={['admin']}><RoleDashboard page="dashboard"/></Guard>}/>{adminPages.map(page=><Route key={page} path={`/admin/${page}`} element={<Guard roles={['admin']}><RoleDashboard page={page}/></Guard>}/>)}<Route path="/" element={<Home/>}/><Route path="*" element={<Home/>}/></Routes></PageErrorBoundary>}
function Home(){const user=useSelector(s=>s.auth.user);return <Navigate to={!user?'/login':user.role==='customer'?'/customer/dashboard':user.role==='agent'?'/agent/dashboard':'/admin/dashboard'} replace/>}
class PageErrorBoundary extends Component{state={hasError:false,error:null};static getDerivedStateFromError(error){return {hasError:true,error}}componentDidCatch(error,info){console.error('Page rendering failed:',error,info)}render(){if(this.state.hasError)return <main className="chat-loading error-boundary"><h1>We couldn’t load this page.</h1><p>Please return to your dashboard and try again.</p>{this.state.error&&<details className="error-detail"><summary>Technical details</summary><pre>{String(this.state.error?.message||this.state.error)}</pre></details>}<div className="error-actions"><button className="outline-button" onClick={()=>this.setState({hasError:false,error:null})}>Try again</button><button className="primary" onClick={()=>{this.setState({hasError:false,error:null});window.location.assign('/')}}>Return to dashboard</button></div></main>;return this.props.children}}
