import User from '../models/User.js';
const fail=(message,status)=>{const error=new Error(message);error.status=status;throw error;};
export async function createAgent({name,email,password,avatar,availability='offline'}) { if(!name?.trim()||!email?.includes('@')||!password||password.length<8) fail('Provide a name, valid email, and password of at least 8 characters',422); if(await User.exists({email:email.toLowerCase()})) fail('An account with this email already exists',409); return User.create({name,email,password,avatar,availability,role:'agent'}); }
export async function listAgents(){return User.find({role:'agent'}).select('name email avatar availability isOnline lastSeen createdAt').sort({name:1});}
export async function updateAgent(id,{name,email,avatar,availability}){const agent=await User.findOne({_id:id,role:'agent'});if(!agent)fail('Agent not found',404);if(name!==undefined){if(typeof name!=='string'||name.trim().length<2||name.trim().length>80)fail('Name must be between 2 and 80 characters',422);agent.name=name.trim();}if(email!==undefined){if(typeof email!=='string'||!email.includes('@'))fail('Valid email required',422);const exists=await User.findOne({email:email.toLowerCase(),_id:{$ne:id}});if(exists)fail('An account with this email already exists',409);agent.email=email.toLowerCase();}if(avatar!==undefined){if(typeof avatar!=='string'||avatar.length>700000)fail('Avatar image is invalid or too large',422);agent.avatar=avatar;}if(availability!==undefined){if(!['online','away','offline'].includes(availability))fail('Invalid availability',422);agent.availability=availability;agent.isOnline=availability==='online';if(availability==='offline')agent.lastSeen=new Date();}await agent.save();return agent;}
export async function deleteAgent(id){const agent=await User.findOneAndDelete({_id:id,role:'agent'});if(!agent)fail('Agent not found',404);return {success:true};}
export async function updateAgentAvailability(id,availability){if(!['online','away','offline'].includes(availability))fail('Invalid availability',422);const agent=await User.findOneAndUpdate({_id:id,role:'agent'},{availability,isOnline:availability==='online',lastSeen:availability==='offline'?new Date():undefined},{new:true});if(!agent)fail('Agent not found',404);return agent;}
export async function updateAvailability(user,availability){if(!['online','away','offline'].includes(availability))fail('Invalid availability',422);user.availability=availability;user.isOnline=availability==='online';if(availability==='offline')user.lastSeen=new Date();await user.save();return user;}
export async function updateProfile(user,{name,avatar}){if(name!==undefined){if(typeof name!=='string'||name.trim().length<2||name.trim().length>80)fail('Name must be between 2 and 80 characters',422);user.name=name.trim();}if(avatar!==undefined){if(typeof avatar!=='string'||avatar.length>700000)fail('Avatar image is invalid or too large',422);user.avatar=avatar;}await user.save();return user;}
